version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - nilerr
    - prealloc
    - revive
  disable:
    - dupl
    - exhaustive
    - funlen
    - gocyclo
    - godot
    - lll
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable:
        - shadow
    revive:
      severity: warning
      rules:
        - name: var-naming
        - name: receiver-naming
        - name: error-strings
        - name: if-return
        - name: early-return
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - urlshortener
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
